# configuration for https://github.com/crate-ci/typos

[default.extend-words]
ratatui = "ratatui"
sectore = "sectore" # https://github.com/sectore

[type.md]
extend-ignore-re = [
  "\\[[[:xdigit:]]{7}\\]\\(https://github.com/ratatui/ratatui/commit/[[:xdigit:]]{40}\\)",
]
