[package]
name = "colors-rgb"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
palette = "0.7.6"
ratatui.workspace = true

[lints]
workspace = true
