[package]
name = "inline"
publish = false
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
color-eyre.workspace = true
crossterm.workspace = true
rand = "0.9.1"
ratatui.workspace = true

[lints]
workspace = true
